BEGIN;

-- Merchants (one row per Shopify store)
CREATE TABLE IF NOT EXISTS merchants (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_domain    TEXT NOT NULL UNIQUE,            -- e.g., acme.myshopify.com
  invoice_email   TEXT,
  currency        CHAR(3) NOT NULL DEFAULT 'USD',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Per-merchant widget configuration
CREATE TABLE IF NOT EXISTS widget_configs (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id  INTEGER NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  placement    TEXT NOT NULL DEFAULT '#main-cart-footer',
  verbiage     TEXT NOT NULL DEFAULT 'to reduce my carbon footprint',
  theme_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Opt-ins captured from the widget / checkout
CREATE TABLE IF NOT EXISTS opt_ins (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id        INTEGER NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
  customer_id        TEXT,
  customer_email     TEXT,
  session_id         TEXT,
  order_ref          TEXT,
  cart_subtotal      NUMERIC(12,2) NOT NULL CHECK (cart_subtotal >= 0),
  currency           CHAR(3) NOT NULL DEFAULT 'USD',
  estimated_offset   NUMERIC(12,3) NOT NULL CHECK (estimated_offset >= 0),
  estimator_version  TEXT,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Helpful indexes for reporting
CREATE INDEX IF NOT EXISTS idx_merchants_store_domain
  ON merchants (store_domain);

CREATE INDEX IF NOT EXISTS idx_optins_merchant_updated_at
  ON opt_ins (merchant_id, updated_at);

CREATE INDEX IF NOT EXISTS idx_optins_merchant_created_at
  ON opt_ins (merchant_id, created_at);

COMMIT;
